version: "3.9"
services:
  mysql:
    image: mysql/mysql-server
    container_name: code6_mysql
    restart: always
    networks:
      - code6-network
    env_file:
      - .env.docker-compose
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MYSQL_VOLUME_PATH}:/var/lib/mysql

  code6:
    build:
      context: .
      dockerfile: Dockerfile
    image: code6
    container_name: code6-server
    depends_on:
      - "mysql"
    links:
      - "mysql"
    restart: always
    networks:
      - code6-network
    env_file:
      - .env.docker-compose
    ports:
      - ${PORT}:80

networks:
  code6-network:
    name: code6-network
