version: "3.9"
services:
  mysql:
    image: mysql/mysql-server
    container_name: code6_mysql
    restart: always
    networks:
      - code6-network
    env_file:
      - .env.docker-compose
    ports:
      # MySQL 端口映射 - 宿主:容器
      - ${MYSQL_PORT}:${MYSQL_PORT_CONTAINER}
    volumes:
      - /etc/localtime:/etc/localtime:ro # 设置容器时区与宿主机保持一致
      - /tmp/mysql:/var/lib/mysql        # 数据持久化

  code6:
    build:
      context: .
      dockerfile: Dockerfile
    image: code6
    container_name: code6-server
    # 依赖服务启动后才启动
    depends_on:
      - "mysql"
    # 直接通过 links 访问数据服务
    links:
      - "mysql"
    restart: always
    networks:
      - code6-network
    env_file:
      - .env.docker-compose
    ports:
      # 端口映射 - 宿主:容器
      - ${PORT}:${PORT_CONTAINER}

networks:
  code6-network:
    driver: bridge
    name: code6-network
